version: '3'

services:
  invoice-app:
    build: .
    container_name: invoice-extractor
    ports:
      - "8501:8501"
    restart: always
    # Cấu hình giới hạn tài nguyên (Optional)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 4G
